[book]
authors = ["Simon Sawert"]
language = "en"
multilingual = false
src = "src"
title = "Book #1"

[preprocessor.links]

[preprocessor.all-the-markdowns]
command = "cargo run --manifest-path=Cargo.toml --bin mdbook-all-the-markdowns"
draft-folders = false
index-names = ["README.md", "default.md"]

[[preprocessor.all-the-markdowns.section]]
title = "Libraries"
base = "./examples/example-folder-structures/slim/my-libraries"
ignore = []

[[preprocessor.all-the-markdowns.section]]
title = "Services"
base = "./examples/example-folder-structures/slim/my-services"
ignore = []

[[preprocessor.all-the-markdowns.section]]
title = "A lot of things"
base = "./examples/example-folder-structures/deep-nested"
ignore = []
